#! /bin/sh

outdir="output"

quitdirhelp()
{
	printf '%s' "\
err: an output directory must have this structure:
<output>
├── 0kb_files
└── uncompiled
      ├── demo
      │     ├── animation (a file containing rules that will be in every generated QC file)
      │     └── (files whose content will only be included if called by name)
      ├── engineer
      └── (and all the other classes)
"
	exit 1
}

writevtx()
{
	dx80="$outdir/0kb_files/${1%.*}.dx80.vtx"
	dx90="$outdir/0kb_files/${1%.*}.dx90.vtx"

	mkdir -p $(dirname "$dx80")
	touch "$dx80" "$dx90"
}

parse()
{
	modelname="$1"
	filename="$2"
	class="$3"

	#if the file is specified as a vtx file, just create them
	if [ "$filename" = "vtx" ]; then
		writevtx "$modelname"
		return
	fi

	shift 3
	files="$@"
	modelname="${modelname#models/}"

	#create the qc files
	(
	cd "$outdir/uncompiled/$class" || exit 1
	printf '$modelname\t"%s"\n' "$modelname" >"$filename"
	cat $files >>"$filename"
	) || quitdirhelp
}


while getopts "o:" a; do
	case "$a" in
	o)	outdir="$OPTARG";;
	esac
done

while read line; do
	parse $line
done <&0
