// Created by Crowbar 0.74

$modelname "player/items/mvm_loot/spy/fob_e_knife_v.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\player\items\mvm_loot\spy\fob_e_knife_v\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"fob_e_knife_v_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
