// Created by Crowbar 0.74

$modelname "workshop/player/items/scout/robo_all_mvm_canteen/robo_all_mvm_canteen.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\workshop\player\items\scout\robo_all_mvm_canteen\robo_all_mvm_canteen\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"robo_all_mvm_canteen_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
