// Created by Crowbar 0.74

$modelname "workshop_partner/weapons/c_models/c_bow_thief/c_bow_thief_festivizer"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\workshop_partner/weapons/c_models/c_bow_thief/c_bow_thief_festivizer\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"c_bow_thief_festivizer_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
