// Created by Crowbar 0.74

$modelname "items\ammopack_large_bday.mdl"

$bodygroup "body"
{
	studio "ammopack_large.smd"
}


$surfaceprop "wood"

$contents "solid"

$illumposition 0.025 -0.02 20.105

$cdmaterials "console\models\items\ammo_large"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hboxset "default"
$hbox 0 "cube" -12.448 -10.156 -12.288 11.74 26.16 13.662


$includemodel "items/anims/medkit-ammopack.mdl"