// Created by Crowbar 0.74

$modelname "workshop/weapons/c_models/c_snub_nose/c_snub_nose_festivizer.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\workshop\weapons\c_models\c_snub_nose\c_snub_nose_festivizer\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"c_snub_nose_festivizer_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
