// Created by Crowbar 0.74

$modelname "player/items/all_class/hwn_spellbook_diary.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\player\items\all_class\hwn_spellbook_diary\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"hwn_spellbook_diary_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
