// Created by Crowbar 0.74

$modelname "player/items/mvm_loot/scout/fob_h_scattergun_diamond.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\player\items\mvm_loot\scout\fob_h_scattergun_diamond\"

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$definebone "dummy_bone" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"fob_h_scattergun_diamond_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
